name: Install required packages
description: Install required packages
runs:
  using: composite
  steps:
    - name: Install packages
      shell: bash
      run: |
        sudo apt-get -y update
        sudo apt-get -y install \
          build-essential cmake \
          git wget rsync jq \
          asterisk-dev libasound2-dev libsqlite3-dev

    - name: Git configuration
      shell: bash
      run: git config --global advice.detachedHead false
