set(CPACK_GENERATOR DEB)
set(CPACK_STRIP_FILES ON)
set(CPACK_SET_DESTDIR ON)

set(CPACK_DEBIAN_FILE_NAME DEB-DEFAULT)
set(CPACK_DEBIAN_PACKAGE_VERSION ${VERSION_STRING})
set(CPACK_DEBIAN_PACKAGE_DEPENDS asterisk)
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Harin Lee <me@harin.net>")
set(CPACK_DEBIAN_PACKAGE_SECTION comm)
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)
set(CPACK_DEBIAN_PACKAGE_RECOMMENDS "usb-modeswitch")

file(COPY cpack/deb DESTINATION cpack
    FILE_PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ
    PATTERN "postinst" PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE
)

set(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA
    ${PROJECT_BINARY_DIR}/cpack/deb/conffiles
    ${PROJECT_BINARY_DIR}/cpack/deb/postinst
)

include(CPack)
