name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: install-dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get -y update
          sudo apt-get -y install \
            build-essential cmake \
            asterisk-dev libasound2-dev libsqlite3-dev

      - name: build
        run: |
          cmake -B build -DCMAKE_INSTALL_PREFIX=/usr
          cmake --build build -j$(nproc)

      - name: package
        run: cmake --build build --target package

      - name: upload-artifact
        uses: actions/upload-artifact@v7
        with:
          name: chan-quectel
          path: |
            build/src/chan_quectel.so
            build/asterisk-chan-quectel*.deb
          if-no-files-found: error
